name: xylo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1  # Downgraded to resolve conflict
  geolocator: ^9.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  page_transition: ^2.1.0
  audioplayers: ^6.1.0
  geocoding: ^3.0.0
  provider: ^6.1.2
  animated_splash_screen: ^1.3.0
  camera: ^0.11.0+2

  
  animated_text_kit: ^4.2.2
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.1
  color: #f5ad42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.png
    - assets/images/google_logo.png
    - assets/gif/ar_view.gif
    - assets/gif/loading_ani.gif
    - assets/music/loading_music.mp3
    - assets/images/login_manual.png
    - assets/gif/login_bg.png


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_background.png
  branding: assets/images/splash_background1.png
  android_12:
    image: assets/images/splash_background.png
    icon_background_color: "#ffffff"
